### ISSUE TITLE
unable to use gitlab-merge-request

### ISSUE THREAD

**Issue by dipysun** [samcontesse/gitlab-merge-request-resource#18] opened 2019-06-12 06:23 UTC
We are trying to use the resource gitlab-merge-request in the concourse pipeline, but seeing the error below

resource script '/opt/resource/check []' failed: exit status 2

stderr:
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/samcontesse/gitlab-merge-request-resource.(*Source).GetProjectPath(0xc000058240, 0xc000090a00, 0x7)
	/go/src/github.com/samcontesse/gitlab-merge-request-resource/models.go:43 +0x88
main.main()
	/go/src/github.com/samcontesse/gitlab-merge-request-resource/check/cmd/main.go:29 +0x288

**Comment by samcontesse** [comment] 2019-06-12 06:40
Can you share your resource configuration ?

**Comment by dipysun** [comment] 2019-06-12 07:04
resource_types:
- name: merge-request
  type: docker-image
  source:
    repository: samcontesse/gitlab-merge-request-resource
    tag: latest
   
resources:
- name: repo-mr
  type: merge-request
  source:
    uri: git@my-git-url:project/myproj.git
    private_key: ((private-repo-key))

- name: git-repo-ci
  type: git
  source:
    uri: git@my-git-url:project/myproj.git
    private_key: ((private-repo-key))

jobs:
  - name: mr-unit-test
    plan:
    - get: git-repo-ci
      trigger: true
    - get: repo-mr
      trigger: true
    - task: get-ci-cd
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: maven
            tag: 3.3.9-jdk-8
        inputs:
          - name: git-repo-ci
          - name: repo-mr
        run:
          path: sh
          args:
          - -exc
          - |
            pwd
            ls

**Comment by samcontesse** [comment] 2019-06-12 07:08
This resource supports only http repository urls.

**Comment by dipysun** [comment] 2019-06-12 08:08
Here is the error after changing to https url 
resource script '/opt/resource/check []' failed: exit status 1

stderr:
error retrieving opened merge requests: GET https://gitlab.xxxxx/api/v4/projects/repo/project/merge_requests: 404 {message: 404 Project Not Found}

I do have a open merge request in that project

**Comment by samcontesse** [comment] 2019-06-12 08:25
Apparently, your configuration (uri) is not pointing to an existing repository `404 Project Not Found`

**Comment by dipysun** [comment] 2019-06-12 09:39
This is definitely an existing repo. Also I tried with other repos. Got the same error. 
Could it be something to do with the versions of api?

**Comment by samcontesse** [comment] 2019-06-13 07:00
Which GitLab version do you have ? Calls are made against v4 API which is default since GitLab 9.0.

**Comment by dipysun** [comment] 2019-06-17 05:35
I tried to embed the key in the yaml file and then it worked.
I need help around retrieving all the open merge requests(MR). The current config only fetches the latest MR.

**Comment by samcontesse** [comment] 2019-06-17 06:43
The resources fetches "opened" merge requests (ordered by updated date). There is no filter applied on this request. Is the user used to connect the repository allowed to see all merge requests ?

**Comment by dipysun** [comment] 2019-06-17 07:09
This is an extract from the json - {...........,"state":"merged","created_at":"2019-06-13T09:16:11.931Z"..........} 
The status for this MR is merged. And I have one more MR that is in open state. 
I dont see the open MR info in the json.

**Comment by samcontesse** [comment] 2019-06-17 07:30
Which GitLab version do you have ?

**Comment by samcontesse** [comment] 2019-06-17 07:34
You can try to call the API using curl or Postman to see what your server gives you back. The request is  `/merge_requests?state=opened&order_by=updated_at` (see also https://docs.gitlab.com/ee/api/merge_requests.html)

**Comment by dipysun** [comment] 2019-06-17 09:07
The api is returning the MR correctly with 'state=opened'. Also, it returns all the MR (in all states) without the filter. 

![image](https://user-images.githubusercontent.com/51735623/59592287-6369ef00-910d-11e9-8c75-1912756bc59f.png)

**Comment by dipysun** [comment] 2019-06-17 09:10
Gitlab version - GitLab Enterprise Edition 11.6.11-ee

**Comment by samcontesse** [comment] 2019-06-19 08:29
I'm re-reading your previous comment and I'm not sure to understand from where you get the JSON ?

> The status for this MR is merged. And I have one more MR that is in open state.
> I dont see the open MR info in the json.

Is there a chance this MR was merged between the `check` would emit the version and the `in` would pick it up and start the build ? Can you check the timestamp in Concourse and in GitLab because I don't see any reason an already merged MR would be built besides re-triggering the build manually (plus button or api).

**Comment by dipysun** [comment] 2019-06-26 09:17
I found out why I could see that MR, Like you pointed out, the MR was merged between the run. But then, I still have one more problem now. Though there are multiple open MR's, only the first (oldest) MR is being printed.
Here is the run part of task

 run:
          path: cat  
          args:
          - '.git/merge-request.json'

**Comment by samcontesse** [comment] 2019-06-26 11:57
I think there is a misunderstanding of the resource concept here. 

* The `check` script lists all open merge requests
* The `in` script (which is used by your job - `get: git-repo-ci`) fetches _one_ and only one MR at the time.

You will only have the MR being fetched in the .git/merge-request.json.

I hope this is clear enough. Maybe the [official documentation](https://concourse-ci.org/implementing-resource-types.html) might help you.

**Comment by dipysun** [comment] 2019-06-26 13:05
I tried to mimic the job in this link. I am updating the MR with a comment. But again I see that only one of them is getting updated.
https://github.com/samcontesse/gitlab-merge-request-resource

Here is the config - 

resource_types:
- name: merge-request
  type: docker-image
  source:
    repository: samcontesse/gitlab-merge-request-resource
    tag: latest
   
resources:
- name: mr-repo-engine
  type: merge-request
  source:
    uri: https://myproject/repo/repo.git
    private_token: ((private-token-http))

jobs:
  - name: check-mr-engine
    plan:
    - get: mr-repo-engine
      trigger: true
    - task: get-mr-repo-engine
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: maven
            tag: 3.3.9-jdk-8
        run:
          path: sh  
          args:
          - -exc
          - |
            ls

    on_failure:
      put: mr-repo-engine
      params:
        repository: mr-repo-engine
        status: failed
        comment: 
          text: |
            Failure - Comment updated by concourse
      
    on_success:
      put: mr-repo-engine
      params:
        repository: mr-repo-engine
        status: success
        comment: 
          text: |
            success - Comment updated by concourse
        
 
What am I missing?

**Comment by samcontesse** [comment] 2019-06-26 14:01
I believe this is the expected behaviour. You _check-mr-engine_ will care of one merge request at the time.

**Comment by dipysun** [comment] 2019-06-27 06:02
How can I update all the MR at one time?

**Comment by dipysun** [comment] 2019-07-01 10:00
I see there are differences between the API(mentioned earlier) response and the concourse resource. The Git API only returns the MR's that are in open state. The concourse resource, fetches the latest MR even if its in close state. 

The intention here is to only fetch those that are in open state. I also tried updating the state to pending,  but the state of the MR is not changing

**Comment by samcontesse** [comment] 2019-07-02 08:54
The resource fetches all open merge requests during the check phase. What you see when you use `get: mr-repo-engine` is only one of them. Imagine a for loop, the array is given by the _check_ script and the _in_ script processes each merge request one at the time.

If we make an analogy with the git resource. It will fetch all commits durning the check phase and then the _in_ script processes only one revision at the time.

**Comment by dipysun** [comment] 2019-07-02 12:14
Thank you. This explains. 

With reference to the below snippet, can you please let me know what the status indicates. 
When I run the pipeline, I see the latest merge request getting updated, irrespective of the status - opened or closed.

on_success:
    put: merge-request
    params:
      repository: merge-request
      status: success
      labels: ['unit-test', 'stage']
      comment:
        file: out/commt.txt
        text: |
          Add new comment.
          $FILE_CONTENT

**Comment by samcontesse** [comment] 2019-07-04 13:33
This resource is designed to be used as trigger for your job. If you trigger the pipeline manually every time, you will end up building the same commit and update the status of the MR even if it was already closed. Concourse pipeline should be designed to be idempotent so I believe this is the expected behaviour.

**Comment by samcontesse** [comment] 2020-07-21 06:15
I’m closing this issue because it has been inactive for more than a year.

**Closed by samcontesse** 2020-07-21 06:15 UTC
